name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'The semver to use'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    steps:
      - uses: nearform-actions/optic-release-automation-action@v4
        with:
          semver: ${{ github.event.inputs.semver }}
          publish-mode: oidc
          build-command: |
            npm install

